// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prrvbzvyqhyoskvootth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBycnZienZ5cWh5b3Nrdm9vdHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NDAxNDAsImV4cCI6MjA3OTMxNjE0MH0.clVFCw_D7lr-L8VAxmjox5a0KDztBSOe8MXgww6EXHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
