// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtzepwocjebeqnfjelmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0emVwd29jamViZXFuZmplbG1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMjIzNDksImV4cCI6MjA3ODc5ODM0OX0.kU3wTum0yFQFKr2TAzQrXzEmnogsg7_wNGsL05svSAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
